<?php

namespace App\Http\Controllers\Modules\Enums;

use App\Helpers\Enum;

class MT5ClientStatus extends Enum
{
    const CLIENT_STATUS_UNREGISTERED = 0;
    const CLIENT_STATUS_REGISTERED = 100;
    const CLIENT_STATUS_NOTINTERESTED = 200;
    const CLIENT_STATUS_APPLICATION_INCOMPLETED = 300;
    const CLIENT_STATUS_APPLICATION_COMPLETED = 400;
    const CLIENT_STATUS_APPLICATION_INFORMATION = 500;
    const CLIENT_STATUS_APPLICATION_REJECTED = 600;
    const CLIENT_STATUS_APPROVED = 700;
    const CLIENT_STATUS_FUNDED = 800;
    const CLIENT_STATUS_ACTIVE = 9000;
    const CLIENT_STATUS_INACTIVE = 1000;
    const CLIENT_STATUS_SUSPENDED = 1100;
    const CLIENT_STATUS_CLOSED = 1200;
    const CLIENT_STATUS_TERMINATED = 1300;
}
